name: CD - Deploy images to Docker Hub
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Enable Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Bootstrap a fresh Docker builder instance
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap

      - name: Build & Push 64-bit Raspberry Pi OS Lite (arm64) to Docker Hub
        run: ./docker-wrapper.sh -a -p

      - name: Build & Push 32-bit Raspberry Pi OS Lite (armhf) to Docker Hub
        run: |
          ./docker-wrapper.sh -H -p
