name: CD - Deploy images to Docker Hub
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Enable Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Bootstrap a fresh Docker builder instance
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap

  deploy:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [arm64, armhf]

    steps:
      - name: Build & Push to Docker Hub
        run: |
          if [ "${{ matrix.platform }}" = "arm64" ]; then
            ./docker-wrapper.sh --arm64 --push
          else
            ./docker-wrapper.sh --armhf-all --push
          fi
