name: CD - Deploy images to Docker Hub
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/cd.yml'
      - '.raspios-versions'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
